Repository O-W-C-A/owca-exam-planner-backend, pull requests merged in 2024-12, with the labels that each got.

#4 Update README.md with data import steps
  README.md
Labels: documentation

#5 Add Precheck & Deploy workflow for CI
  .github/workflows/ASP-Deploy.yml
  .github/workflows/Precheck-Deploy.yml
  .github/workflows/master_api20241122192439.yml
Labels: enhancement

#8 Use different database connection string based on env
  API/Program.cs
Labels: bug

#9 Test Deploy to azure from test branch
  .github/workflows/TestDeploy.yml
Labels: enhancement

#14 WIP workflow check
  .github/workflows/wip.yml
Labels: wip

#16 Fix error on multiple label check
  .github/workflows/wip.yml
Labels: bug

#17 Login Handling JWT token and secrets
  API/API.csproj
  API/Controllers/AddInDBController.cs
  API/Controllers/UserController.cs
  API/Models/LoginUser.cs
  API/Program.cs
  API/appsettings.json
Labels: enhancement

#18 Fix compile errors
  API/Services/FacultyService.cs
Labels: bug

#19 Adaugare de roomsand f ixes
  API/Controllers/ExamController.cs
Labels: enhancement
